[build]
base = "frontend"
command = "npm ci && npm run build"
publish = "build"

[build.environment]
ADAPTER = "netlify"
NODE_VERSION = "22"
SECRETS_SCAN_OMIT_KEYS = "OPENAI_BASE_URL"
MONGODB_DB_NAME = "masterthesis-buddy"

[functions]
node_bundler = "esbuild"
